# Setup
title:               James' Dev log
tagline:             'Personal Dev Blog'
description:         ''
url:                 https://jamesj0918.github.io/
baseurl:             '/'
production_url:      https://jamesj0918.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James Jung
  url:               
  email:             jamesj0107@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
