# Setup
title:               James' Dev log
tagline:             '&nbsp;Personal Dev Blog'
description:         ''
url:                 
baseurl:             'https://jamesj0918.github.io/'
production_url:      https://jamesj0918.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James Jung
  url:               https://www.instagram.com/therealjamesjung/
  email:             jamesj0107@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: UA-176741319-1

markdown: kramdown
mathjax: true